boosting_type: "gbdt"
num_leaves: 31
max_depth: -1
learning_rate: 0.1
n_estimators: 100
subsample_for_bin: 200000
objective:
class_weight:
min_split_gain: 0.0
min_child_weight: 0.001
min_child_samples: 20
subsample: 1.0
subsample_freq: 0
colsample_bytree: 1.0
reg_alpha: 0.0
reg_lambda: 0.0
random_state:
n_jobs:
importance_type: "split"
