# """ https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html#sklearn.svm.SVR """
kernel: 'rbf' 
# description: specifies the kernel type to be used in the algorithm
# default: 'rbf'
# options: ['linear', 'rbf', 'sigmoid', 'precomputed']