# """ https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html#sklearn.svm.SVR """

kernel: 'rbf' 
# description: specifies the kernel type to be used in the algorithm
# default: 'rbf'
# options: 'linear', 'rbf', 'sigmoid', 'precomputed'

degree: 3
# description: Degree of the polynomial kernel function (‘poly’). Must be non-negative. Ignored by all other kernels. 
# default: 3
# options:

gamma: 'scale'
# description: Kernel coefficient for ‘rbf’, ‘poly’ and ‘sigmoid’.
# default: 'scale'
# options: 'scale', 'auto', float: range [0, inf]

coef0: 0.0
# description: Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
# default: 0.0
# options:

tol: 0.001
# description: Tolerance for stopping criterion.
# default: 1e-3
# options:

C: 1.0
# description: Regularization parameter. The strength of the regularization is inversely proportional to C. Must be strictly positive. The penalty is a squared l2 penalty.
# default: 1.0
# options:

epsilon: 0.1
# description: Epsilon in the epsilon-SVR model. It specifies the epsilon-tube within which no penalty is associated in the training loss function with points predicted within a distance epsilon from the actual value.
# default: 0.1
# options: float: range [0, inf]

shrinking: True
# description: Whether to use the shrinking heuristic.
# default: True
# options: True, False

cache_size: 200
# description: Specify the size of the kernel cache (in MB). 
# default: 200
# options: 

verbose: True
# description: Enable verbose output. Note that this setting takes advantage of a per-process runtime setting in libsvm that, if enabled, may not work properly in a multithreaded context.
# default: False
# options: True, False

max_iter: -1
# description: Hard limit on iterations within solver, or -1 for no limit. 
# default: -1
# options: